### ISSUE TITLE
Setup word press in local machine.

### ISSUE THREAD

**Issue by Demonbruster** [Demonbruster/todo-app#16]
- [x] Download the XAMPP or WAMP server and install it on your local machine. (https://www.apachefriends.org/download.html)
- [x] Create MySQL DB for WordPress
- [x] Install WordPress.

**Comment by thisisfaaris** [comment]
1. Setup Local - Download WordPress + Add theme and plugins + Install XAMPP + Configure Environment
2. Buy domain and hosting provider + Add theme and plugins

**Comment by Demonbruster** [comment]
YT reference: https://www.youtube.com/watch?v=a2Dxb9jZK1I

**Comment by thisisfaaris** [comment]
![Image](https://github.com/Demonbruster/todo-app/assets/49782800/db3dde4d-5423-4d22-a3e2-bf5d8bb6ca4d)

**Comment by Demonbruster** [comment]
> ![Image](https://private-user-images.githubusercontent.com/49782800/303232630-db3dde4d-5423-4d22-a3e2-bf5d8bb6ca4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTk5NjQsIm5iZiI6MTcwNzM5OTY2NCwicGF0aCI6Ii80OTc4MjgwMC8zMDMyMzI2MzAtZGIzZGRlNGQtNTQyMy00ZDIyLWEzZTItYmY1ZDhiYjZjYTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEzNDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYTE2MWNiYmZkYmZjMDY4ZDA1OTA2NmM0OTc0ODlkNjdhMzMyNDUzNGU5YjUxYzQ3OTUyZWY1YjY3YTViNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JvJzAiQDRfMpDpqBk7kv-Q_2CkUihkiKS6x3cxaYyi0)

Awesome Keep going @thisisfaaris
