### ISSUE TITLE
Adding new task

### ISSUE THREAD

**Issue by Demonbruster** [Demonbruster/todo-app#2]
There must be a add task  Plus button,
Once click the plus button should popup a textbox,
Once filling the task should able to submit by clicking submit  button,
once after click the submit button it should be validated (like avoiding Empty box),
API endpoints
database configuration with task tables and Task Status table,

**Comment by thisisfaaris** [comment]
- [ ] Create a component for adding new tasks.
- [ ] Use state to manage the input field.
- [ ] Handle form submission to send data to the server.

**Comment by Demonbruster** [comment]
xcvxzc
