### ISSUE TITLE
Create delete btn

### ISSUE THREAD

**Issue by Demonbruster** [Demonbruster/todo-app#4]
add a delete button next to each tasks, 
once clicked it should pop up delete confirmation and delete
API endpoint for deletion (Logic for deletion)
Implement delete functionality

**Comment by thisisfaaris** [comment]
- [ ] Implement a delete button in the task list component.
- [ ] Create a route in the Express server to handle task deletion.

**Comment by thisisfaaris** [comment]
Develop a delete button component that allows users to remove a task. Upon clicking the delete button, the associated task should be deleted from both the frontend display and the backend storage.
