### ISSUE TITLE
Edit btn

### ISSUE THREAD

**Issue by Demonbruster** [Demonbruster/todo-app#5]
When select edit btn of a single item of the list; it should comes under the input component as editable.

**Comment by thisisfaaris** [comment]
- [ ] Create a component for editing tasks.
- [ ] Add an edit button in the task list component.
- [ ] Create a route in the Express server to handle task updates.

**Comment by DmAsnaff** [comment]
Implement Edit button,
When select edit btn of a single item of the list; it should comes under the input component as editable. (logic for edit or update),
Create API endpoint for editing 
edit or update functionality in database,

**Comment by thisisfaaris** [comment]
Implement an edit button component to enable users to modify existing tasks. Clicking on the edit button should trigger a task edit popup component where users can edit the task details. Ensure that the changes are reflected in both the frontend display and backend storage.
