### ISSUE TITLE
Mark as Completed

### ISSUE THREAD

**Issue by Demonbruster** [Demonbruster/todo-app#6]
When click the task it should mark as complete.

**Comment by thisisfaaris** [comment]
- [ ] Add a feature to mark tasks as completed.
- [ ] Update the server route and database accordingly.

**Comment by DmAsnaff** [comment]
Add a checkbox next to each task to mark it as completed,
logic to update the status of a task to completed in the database.
Write queries to update the completion status of a task in the database.
